---
title: "Developing Data Products"
author: "Evgeniia Golovina"
date: "24/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results="hide")
```

## Developing Data Products course (Coursera)

Week 1

```{r week_1}
#install.packages("shiny")
library(shiny)
# http://shiny.rstudio.com/tutorial/
setwd(paste0(getwd(), "/coursera/data_science_specialisation_JHU/developing_data_products/my_app"))
runApp() # to run app
runApp("path_to_the_app")
?builder # HTML tags in shiny

# ui.R
shinyUI(pageWithSidebar(
  headerPanel("Illustrating markup"),
  sidebarPanel(
      h1('Sidebar panel'),
      h1('H1 text'),
      h2('H2 Text'),
      h3('H3 Text'),
      h4('H4 Text')
  ),
  mainPanel(
      h3('Main Panel text'),
      code('some code'),
      p('some ordinary text')
  )
))

# sliderInput() # create slider and display it; labels have to match!
# ui.R
shinyUI(fluidPage(
  titlePanel("Slider App"),
  sidebarLayout(
    sidebarPanel(
      h1('Move the slider!'),
      sliderInput("slider2", "Slide Me!", 0, 100, 0)
  ),
  mainPanel(
      h3('Slider Value:'),
      textOutput("text1")
  ))
))
# server.R
shinyServer(function(input, output) {
  output$text1 = renderText(input$slider2)
})

# Illustrating inputs ui.R
# ui.R
shinyUI(pageWithSidebar(
    headerPanel("Illustrating inputs"),
    sidebarPanel(
        numericInput('id1', 'Numeric input, labeled id1', 0, min = 0, max = 10, step = 1),
        checkboxGroupInput("id2", "Checkbox",
                           c("Value 1" = "1",
                             "Value 2" = "2",
                             "Value 3" = "3")),
        dateInput("date", "Date:")  
    ),
    mainPanel(
        h3('Illustrating outputs'),
        h4('You entered'),
        verbatimTextOutput("oid1"),
        h4('You entered'),
        verbatimTextOutput("oid2"),
        h4('You entered'),verbatimTextOutput("odate")
    )
))
# server.R
shinyServer(function(input, output) {
    output$oid1 <- renderPrint({input$id1})
    output$oid2 <- renderPrint({input$id2})
    output$odate <- renderPrint({input$date})
})

# Building a prediction function
# ui.R
shinyUI(
  pageWithSidebar(
    # Application title
    headerPanel("Diabetes prediction"),
  
    sidebarPanel(
      numericInput('glucose', 'Glucose mg/dl', 90, min = 50, max = 200, step = 5),
      submitButton('Submit')
    ),
    mainPanel(
        h3('Results of prediction'),
        h4('You entered'),
        verbatimTextOutput("inputValue"),
        h4('Which resulted in a prediction of '),
        verbatimTextOutput("prediction")
    )
  )
)
# server.R
diabetesRisk <- function(glucose) glucose / 200

shinyServer(
  function(input, output) {
    output$inputValue <- renderPrint({input$glucose})
    output$prediction <- renderPrint({diabetesRisk(input$glucose)})
  }
)

# image example
# ui.R
shinyUI(pageWithSidebar(
  headerPanel("Example plot"),
  sidebarPanel(
    sliderInput('mu', 'Guess at the mean',value = 70, min = 62, max = 74, step = 0.05,)
  ),
  mainPanel(
    plotOutput('newHist')
  )
))
# server.R
library(UsingR)
data(galton)

shinyServer(
  function(input, output) {
    output$newHist <- renderPlot({
      hist(galton$child, xlab='child height', col='lightblue',main='Histogram')
      mu <- input$mu
      lines(c(mu, mu), c(0, 200),col="red",lwd=5)
      mse <- mean((galton$child - mu)^2)
      text(63, 150, paste("mu = ", mu))
      text(63, 140, paste("MSE = ", round(mse, 2)))
      })
    
  }
)

# Random numbers plot
# ui.R
library(shiny)
shinyUI(fluidPage(
    titlePanel("Plot Random Numbers"),
    sidebarLayout(
        sidebarPanel(
            numericInput("numeric", "How many random numbers should be plotted?",
                         value = 1000, min = 1, max = 1000, step = 1),
            sliderInput("sliderX", "Pick minimum and maximum x values",
                        -100, 100, value = c(-50, 50)),
            sliderInput("sliderY", "Pick minimum and maximum y values",
                        -100, 100, value = c(-50, 50)),
            checkboxInput("show_xlab", "Show/hide x axis label", value = TRUE),
            checkboxInput("show_ylab", "Show/hide y axis label", value = TRUE),
            checkboxInput("show_title", "Show/hide title")
        ),
        mainPanel(
            h3('graph of random points'),
            plotOutput("plot1")
        )
    )
))
# server.R
library(shiny)
library(UsingR)
data(galton)
shinyServer(function(input, output) {
        output$plot1 <- renderPlot({
            set.seed(2016-05-25)
            number_of_points <- input$numeric
            minX <- input$sliderX[1]
            maxX <- input$sliderX[2]
            minY <- input$sliderY[1]
            maxY <- input$sliderY[2]
            dataX <- runif(number_of_points, minX, maxX)
            dataY <- runif(number_of_points, minY, maxY)
            xlab <- ifelse(input$show_xlab, "X axis", "")
            ylab <- ifelse(input$show_ylab, "Y axis", "")
            main <- ifelse(input$show_title, "Title", "")
            plot(dataX, dataY, xlab=xlab, ylab=ylab, main=main,
                 xlim = c(-100,100), ylim=c(-100,100))
        })
    }
)

# Reactivity
# the reactive statements server.R functions seemingly follow different rules than ordinary R functions.
# Code in reactive functions of shinyServer get run repeatedly as needed when new values are entered. Reactive functions are those like renderPlot and renderPrint
# Example with prediction
# ui.R
library(shiny)
shinyUI(fluidPage(
    titlePanel("Predict Horsepower from MPG"),
    sidebarLayout(
        sidebarPanel(
            sliderInput("sliderMPG", "What is the MPG of the car?", 10, 35, value = 20),
            checkboxInput("showModel1", "Show/hide Model 1", value = TRUE),
            checkboxInput("showModel2", "Show/hide Model 2", value = TRUE),
            submitButton("Submit")
        ),
        mainPanel(
            plotOutput("plot1"),
            h3('Predicted Horsepower from Model 1:'),
            textOutput("pred1"),
            h3('Predicted Horsepower from Model 2:'),
            textOutput("pred2")
        )
    )
))
# server.R
library(shiny)
shinyServer(function(input, output) {
    mtcars$mpgsp <- ifelse(mtcars$mpg - 20 > 0, mtcars$mpg - 20, 0)
    model1 <- lm(hp ~ mpg, data = mtcars)
    model2 <- lm(hp ~ mpgsp + mpg, data = mtcars)
    
    model1pred <- reactive({
        mpgInput <- input$sliderMPG
        predict(model1, newdata = data.frame(mpg = mpgInput))
    })
    
    model2pred <- reactive({
        mpgInput <- input$sliderMPG
        predict(model2, newdata = data.frame(mpg = mpgInput,
                                             mpgsp = ifelse(mpgInput - 20 > 0,
                                                            mpgInput - 20, 0)))
    })
    
        output$plot1 <- renderPlot({
            mpgInput <- input$sliderMPG
            
            plot(mtcars$mpg, mtcars$hp, xlab = "Miles per gallon",
                 ylab = "Horsepower", bty = "n", pch = 16,
                 xlim = c(10, 35), ylim = c(50, 350))
            if(input$showModel1){
                abline(model1, col = "red", lwd = 2)
            }
            if(input$showModel2){
                model2lines <- predict(model2, newdata = data.frame(
                    mpg = 10:35, mpgsp = ifelse(10:35 - 20 > 0, 10:35 - 20, 0)
                ))
                lines(10:35, model2lines, col = "blue", lwd = 2)
            }
            legend(25, 250, c("Model 1 Prediction", "Model 2 Prediction"), pch = 16,
                   col = c("red", "blue"), bty = "n", cex = 1.2)
            points(mpgInput, model1pred(), col = "red", pch = 16, cex = 2)
            points(mpgInput, model2pred(), col = "blue", pch = 16, cex = 2)
        })
        output$pred1 <- renderText({
            model1pred()
        })
        output$pred2 <- renderText({
            model2pred()
        })
    }
)

# Advanced UI
# Examples to use tabs: tabsetPanel(), tabPanel()
# ui.R
library(shiny)
shinyUI(fluidPage(
    titlePanel("Tabs!"),
    sidebarLayout(
        sidebarPanel(
            textInput("box1", "Enter tab 1 text:", value = "Tab 1!"),
            textInput("box2", "Enter tab 2 text:", value = "Tab 2!"),
            textInput("box3", "Enter tab 3 text:", value = "Tab 3!")
        ),
        mainPanel(
            tabsetPanel(type = "tabs",
                        tabPanel("Tab 1", br(), textOutput("out1")),
                        tabPanel("Tab 2", br(), textOutput("out2")),
                        tabPanel("Tab 3", br(), textOutput("out3"))
                        )
        )
    )
))
# server.R
library(shiny)
shinyServer(function(input, output) {
    output$out1 <- renderText(input$box1)
    output$out2 <- renderText(input$box2)
    output$out3 <- renderText(input$box3)
    }
)

# Interactive graphics: using brushedPoints
# ui.R
library(shiny)
shinyUI(fluidPage(
    titlePanel("Visualize Many Models!"),
    sidebarLayout(
        sidebarPanel(
            h3("Slope"),
            textOutput("slopeOut"),
            h3("Intercept"),
            textOutput("intOut")
        ),
        mainPanel(
            plotOutput("plot1", brush = brushOpts(
                id = "brush1"
            ))
        )
    )
))
# server.R
library(shiny)
shinyServer(function(input, output) {
    model <- reactive({
        brushed_data <- brushedPoints(trees, input$brush1,
                                      xvar = "Girth", yvar = "Volume")
        if(nrow(brushed_data) < 2){
            return(NULL)
        }
        lm(Volume ~ Girth, data = brushed_data)
    })
    output$slopeOut <- renderText({
        if(is.null(model())){
            "No model found"
        } else {
            model()[[1]][2]
        }
    })
    output$intOut <- renderText({
        if(is.null(model())){
            "No model found"
        } else {
            model()[[1]][1]
        }
    })
    output$plot1 <- renderPlot({
        plot(trees$Girth, trees$Volume, xlab = "Girth", ylab = "Volume",
             main = "Tree measurments",
             cex = 1.5, pch = 16, bty = "n")
        if(!is.null(model())){
            abline(model(), col = "blue", lwd = 2)
        }
    })
    }
)

# Shiny gadgets
library(shiny); library(miniUI)
myFirstGadget <- function(){
  ui <- miniPage(
    gadgetTitleBar("My First Gadget")
  )
  server <- function(input, output, session){
    observeEvent(input$done, {
      stopApp()
    })
  }
  runGadget(ui, server)
}
myFirstGadget()
# Multiply numbers
multiplyNumbers <- function(numbers1, numbers2){
  ui <- miniPage(
    gadgetTitleBar("Multiply Two Numbers"),
    miniContentPanel(
      selectInput("num1", "First Number", choices=numbers1),
      selectInput("num2", "Second Number", choices=numbers2)
    )
  )
    server <- function(input, output, session){
      observeEvent(input$done, {
        num1 <- as.numeric(input$num1)
        num2 <- as.numeric(input$num2)
        stopApp(num1 * num2)
      })
    }
  runGadget(ui, server)
}
multiplyNumbers(1:10, 1:10)
# Gadgets with interactive graphics
pickTrees <- function(){
  ui <- miniPage(
    gadgetTitleBar("Select points by dragging your mouse"),
    miniContentPanel(
      plotOutput("plot", height = "100%", brush = "brush")
    )
  )
  server <- function(input, output, session){
    output$plot <- renderPlot({
      plot(trees$Girth, trees$Volume, main = "Trees!",
           xlab = "Girth", ylab = "Volume")
    })
    observeEvent(input$done, {
      stopApp(brushedPoints(trees, input$brush, xvar = "Girth", yvar = "Volume"))
    })
  }
  runGadget(ui, server)
}
pickTrees()

# GoogleVis charts
#Motion charts:  `gvisMotionChart`
#Interactive maps: `gvisGeoChart`
#Interactive tables: `gvisTable`
#Line charts: `gvisLineChart`
#Bar charts: `gvisColumnChart`
#Tree maps: `gvisTreeMap`
# Motion chart
suppressPackageStartupMessages(library(googleVis))
M <- gvisMotionChart(Fruits, "Fruit", "Year",
                     options=list(width=600, height=400))
print(M,"chart")
plot(M)
# plots on maps
G <- gvisGeoChart(Exports, locationvar="Country",
                  colorvar="Profit",options=list(width=600, height=400))
print(G,"chart")
plot(G)
# specifying the region
G2 <- gvisGeoChart(Exports, locationvar="Country",
                  colorvar="Profit",options=list(width=600, height=400,region="150"))
plot(G2)
# line chart, setting more options
df <- data.frame(label=c("US", "GB", "BR"), val1=c(1,3,4), val2=c(23,12,32))
Line <- gvisLineChart(df, xvar="label", yvar=c("val1","val2"),
        options=list(title="Hello World", legend="bottom",
                titleTextStyle="{color:'red', fontSize:18}",                         
                vAxis="{gridlines:{color:'red', count:3}}",
                hAxis="{title:'My Label', titleTextStyle:{color:'blue'}}",
                series="[{color:'green', targetAxisIndex: 0}, 
                         {color: 'blue',targetAxisIndex:1}]",
                vAxes="[{title:'Value 1 (%)', format:'##,######%'}, 
                                  {title:'Value 2 (\U00A3)'}]",                          
                curveType="function", width=500, height=300                         
                ))
plot(Line)
# combining multiple plots together
G <- gvisGeoChart(Exports, "Country", "Profit",options=list(width=200, height=100))
T1 <- gvisTable(Exports,options=list(width=200, height=270))
M <- gvisMotionChart(Fruits, "Fruit", "Year", options=list(width=400, height=370))
GT <- gvisMerge(G,T1, horizontal=FALSE)
GTM <- gvisMerge(GT, M, horizontal=TRUE,tableOptions="bgcolor=\"#CCCCCC\" cellspacing=10")
plot(GTM)
# see the HTML code
M <- gvisMotionChart(Fruits, "Fruit", "Year", options=list(width=600, height=400))
print(M)
print(M, 'chart', file='myfilename.html')
# for more info
demo(googleVis)
## plotly
library(plotly)
# basic scatterplot
plot_ly(mtcars, x = mtcars$wt, y = mtcars$mpg, mode = "markers")
plot_ly(mtcars, x = mtcars$wt, y = mtcars$mpg, mode = "markers", color = as.factor(mtcars$cyl))
plot_ly(mtcars, x = mtcars$wt, y = mtcars$mpg, mode = "markers", color = mtcars$disp)
plot_ly(mtcars, x = mtcars$wt, y = mtcars$mpg, mode = "markers", 
        color = as.factor(mtcars$cyl), size = mtcars$hp)
# 3D scatterplot
set.seed(2016-07-21)
temp <- rnorm(100, mean = 30, sd = 5)
pressue <- rnorm(100)
dtime <- 1:100
plot_ly(x = temp, y = pressue, z = dtime, type = "scatter3d", mode = "markers", color = temp)
# line graph
data("airmiles")
plot_ly(x = time(airmiles), y = airmiles)
# multi-line graph
library(plotly); library(tidyr); library(dplyr)
data("EuStockMarkets")
stocks <- as.data.frame(EuStockMarkets) %>%
  gather(index, price) %>% # convert from short format to long format
  mutate(time = rep(time(EuStockMarkets), 4))
plot_ly(stocks, x = stocks$time, y = stocks$price, color = stocks$index)
# histogram
plot_ly(x = precip, type = "histogram")
# boxplot
plot_ly(iris, y = iris$Petal.Length, color = iris$Species, type = "box")
# heatmap
terrain1 <- matrix(rnorm(100*100), nrow = 100, ncol = 100)
plot_ly(z = terrain1, type = "heatmap")
# 3D surface
terrain2 <- matrix(sort(rnorm(100*100)), nrow = 100, ncol = 100)
plot_ly(z = terrain2, type = "surface")
# choropleth maps
state_pop <- data.frame(State = state.abb, Pop = as.vector(state.x77[,1]))
state_pop$hover <- with(state_pop, paste(State, '<br>', "Population:", Pop))
borders <- list(color = toRGB("red"))
map_options <- list(scope = 'usa', projection = list(type = "albers usa"),
                    showlakes = TRUE, lakecolor = toRGB("white"))
plot_ly(state_pop, z = state_pop$Pop, text = state_pop$hover, locations = state_pop$State,
        type = "choropleth", locationmode = "USA-states", color = state_pop$Pop,
        colors = "Blues", marker = list(line = borders)) %>%
  layout(title = "US Population in 1975", geo = map_options)
# ggplotly - convert ggplot to plotly
set.seed(100)
d <- diamonds[sample(nrow(diamonds), 1000),]
p <- ggplot(data = d, aes(x = carat, y = price)) +
  geom_point(aes(text = paste("Clarity:", clarity)), size = 4) +
  geom_smooth(aes(colour = cut, fill = cut)) + facet_wrap(~ cut)
(gg <- ggplotly(p))
plotly_POST(gg) # to post to the plotly website
# Set environment variables (check the plotly API website): plotly_username and plotly_api_key
```

Week 1 Quiz

```{r week_1_quiz}
# Quiz 1
# Q1 - A server.R file containing a call to shinyServer() and A ui.R file containing a call to shinyUI()
# Q2 - Missing a comma in the sidebar panel  
# Q3 - The server.R output name isn't the same as the plotOutput command used in ui.R.
# Q4 - Shiny Gadgets are designed to have small user interfaces that fit on one page; Shiny Gadgets are designed to be used by R users in the middle of a data analysis.
# Q5 - No arguments are defined for pickXY()
```

Week 2

```{r week_2}
## Week 2
# R Markdown
#*** - A slide without a title
# eval = FALSE - to show only code
# Leaflet
setwd(paste0(getwd(), "/coursera/data_science_specialisation_JHU/developing_data_products/w2/pa1"))
library(leaflet)
# generate world map
my_map <- leaflet() %>%
  addTiles() %>%
  addMarkers(lat=39.2980803, lng=-76.5898801, popup="My office")
my_map
# adding many markers
set.seed(2016-04-25)
df <- data.frame(lat = runif(20, min = 39.2, max = 39.3),
                 lng = runif(20, min = -76.6, max = -76.5))
df %>% 
  leaflet() %>%
  addTiles() %>%
  addMarkers()
# Making custom markers
ligginsIcon <- makeIcon(
  iconUrl = "https://pbs.twimg.com/profile_images/690310721184215040/CB72os0s_400x400.jpg",
  iconWidth = 31*215/230, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16
)
# add links
liginsSite <-c(
  "<a href='https://www.auckland.ac.nz/en/liggins.html'>Liggins Institute</a>"
)
my_map <- leaflet() %>%
  addTiles() %>%
  addMarkers(lat=-36.86204830722877, lng=174.76937083810773, popup=liginsSite,
             icon=ligginsIcon)
my_map
# mapping clusters
set.seed(2016-04-25)
df <- data.frame(lat = runif(100, min = 39.2, max = 39.3),
                 lng = runif(100, min = -76.6, max = -76.5))
df %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers(clusterOptions = markerClusterOptions())
# adding circles
set.seed(2016-04-25)
df <- data.frame(lat = runif(20, min = 39.2, max = 39.3),
                 lng = runif(20, min = -76.6, max = -76.5))
df %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers()
# drawing circles
?addCircles
# drawing rectangles
?addRectangles
# adding legends
set.seed(2016-04-25)
df <- data.frame(lat = runif(20, min = 39.2, max = 39.3),
                 lng = runif(20, min = -76.6, max = -76.5),
                 col = sample(c("red", "blue", "green"), 20, replace = TRUE),
                 stringsAsFactors = FALSE)
df %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(color = df$col) %>%
  addLegend(labels = LETTERS[1:3], colors = c("blue", "red", "green"))
```

Week 2 Quiz

```{r week_2_quiz}
# Quiz 2
# Q1 - A format that can be interpreted into markdown (which is a simplified markup language); A simplified format that, when interpreted, incorporates your R analysis into your document.
# Q2 - echo = FALSE
# Q3 - eval = FALSE
# Q4 - An R package interface to the javascript library of the same name; A javascript library for creating interactive maps
# Q5 - leaflet(df) %>% addTiles(); addTiles(leaflet(df))
# Q6 - addMarkers
```

Week 3

```{r week_3}
# R packages
# R classes and methods
?methods; library(methods) # the code for implementing S4 classes/methods in R is in the methods package
?Classes; ?Methods; ?setClass; ?setMethod; ?setGeneric
methods("mean")
show; showMethods("show")
getS3method() # to print a code for a function for S3
getMethod() # to print a code for a function for S4
head(getS3method("mean", "default"), 10)
# creating a polygon class; the slots for the class are x and y
setClass("polygon",
         representation(x = "numeric",
                        y = "numeric"))
# creating a plot method for polygon class
setMethod("plot", "polygon",
          function(x, y, ...){
            plot(x@x, x@y, type = "n", ...)
            xp <- c(x@x, x@x[1])
            yp <- c(x@y, x@y[1])
            lines(xp, yp)
          })
```

Week 3 Quiz

```{r week_3_quiz}
# Quiz 3
# Q1 - An explicit software license
# Q2 - predict, mean, show
# Q3 - getMethod()
# Q4 - #' This function calculates the mean; #'#' @param x is a numeric vector; #' @return the mean of x; #' @export; #' @examples; #' x <- 1:10; #' createmean(x)
```

Week 4

```{r week_4}

```

